project_id = "hfcpwmzmymkibrvsbgry"

[functions.generate-workout-feedback]
verify_jwt = false

[functions.generate-performance-feedback]
verify_jwt = false

[functions.adapt-workout]
verify_jwt = false

[functions.mandatory-adapt-workout]
verify_jwt = false

[functions.extract-time-from-screenshot]
verify_jwt = false

[functions.generate-preworkout-message]
verify_jwt = false
