project_id = "hfcpwmzmymkibrvsbgry"

[functions.generate-workout-feedback]
verify_jwt = false

[functions.generate-performance-feedback]
verify_jwt = false

[functions.adapt-workout]
verify_jwt = false

[functions.mandatory-adapt-workout]
verify_jwt = false

[functions.extract-time-from-screenshot]
verify_jwt = false

[functions.generate-preworkout-message]
verify_jwt = false

[functions.create-coach-user]
verify_jwt = false

[functions.update-coach-password]
verify_jwt = false

[functions.suspend-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true
