/**
 * blockDisplayUtils.ts - Utilitários para exibição de blocos de treino
 * 
 * ═══════════════════════════════════════════════════════════════════════════════
 * MODELO DETERMINÍSTICO DE SEPARAÇÃO TREINO vs COMENTÁRIO (MVP0)
 * ═══════════════════════════════════════════════════════════════════════════════
 * 
 * O motor NÃO interpreta texto. O motor APENAS classifica por MARCADOR.
 * 
 * MARCADORES OFICIAIS:
 * - `= TREINO` → Início do bloco de treino (header)
 * - `-` → Item executável de treino (deve ter métrica objetiva)
 * - `> COMENTÁRIO` ou `>` → Observação do coach
 * 
 * REGRA DE FLUXO:
 * - Texto após `= TREINO` é treino até encontrar `>`
 * - Texto após `>` é comentário até mudar o marcador
 * - Linha sem marcador segue o marcador anterior
 * 
 * FALLBACKS (para textos legados):
 * 1. TAGS: [TREINO], [COMENTÁRIO] — split por região
 * 2. HEURÍSTICA: padrões de comentário (último recurso)
 * 
 * REGRA CRÍTICA:
 * - Comentário NUNCA passa por parser de treino
 * - Comentário NUNCA vira exercício
 * - Linha de treino sem métrica = WARNING
 */

import { BLOCK_CATEGORIES } from '@/utils/categoryValidation';

/**
 * Interface flexível para aceitar diferentes estruturas de bloco
 */
interface BlockLike {
  title?: string | null;
  name?: string | null;
  blockTitle?: string | null;
  headerTitle?: string | null;
  type?: string | null;
  category?: string | null;
}

/**
 * Resultado do getBlockHeader
 */
export interface BlockHeaderResult {
  headerTitle: string;
  headerMeta: string | null;
}

/**
 * Helper para pegar o primeiro valor não-vazio de múltiplos candidatos
 */
function firstNonEmpty(...values: (string | null | undefined)[]): string | null {
  for (const v of values) {
    const trimmed = v?.trim();
    if (trimmed && trimmed.length > 0) {
      return trimmed;
    }
  }
  return null;
}

/**
 * Verifica se um título é auto-gerado ("Bloco X", "BLOCO X", "Treino")
 */
function isAutoGeneratedTitle(title: string | null | undefined): boolean {
  if (!title) return true;
  const trimmed = title.trim();
  if (!trimmed) return true;
  
  // Padrões considerados auto-gerados
  if (/^Bloco \d+$/i.test(trimmed)) return true;
  if (/^BLOCO \d+$/i.test(trimmed)) return true;
  if (trimmed.toLowerCase() === 'treino') return true;
  if (trimmed.toLowerCase() === 'novo bloco') return true;
  
  return false;
}

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * FUNÇÃO PRINCIPAL: getBlockHeader
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * Retorna { headerTitle, headerMeta } para uso em preview e tela do atleta.
 * 
 * REGRA:
 * - Se existe título real → mostrar título real
 * - Se não existe → fallback "Bloco X"
 * - headerMeta = categoria (se existir)
 */
export function getBlockHeader(block: BlockLike, index: number): BlockHeaderResult {
  // 1) Buscar título em múltiplos campos possíveis
  const titleCandidate = firstNonEmpty(
    block.title,
    block.name,
    block.blockTitle,
    block.headerTitle
  );
  
  // 2) Determinar displayTitle (ignorar auto-gerados)
  let displayTitle: string | null = null;
  if (titleCandidate && !isAutoGeneratedTitle(titleCandidate)) {
    displayTitle = titleCandidate;
  }
  
  // 3) Determinar categoria
  const categoryRaw = firstNonEmpty(block.type, block.category);
  let displayCategory: string | null = null;
  
  if (categoryRaw) {
    // Buscar label amigável na lista de categorias
    const categoryInfo = BLOCK_CATEGORIES.find(c => c.value === categoryRaw);
    displayCategory = categoryInfo ? categoryInfo.label : categoryRaw;
  }
  
  // 4) Header final
  const headerTitle = displayTitle ?? `Bloco ${index + 1}`;
  const headerMeta = displayCategory ?? null;
  
  return { headerTitle, headerMeta };
}

/**
 * Versão simplificada: retorna apenas o título
 */
export function getBlockDisplayTitle(
  block: BlockLike,
  blockIndex: number
): string {
  return getBlockHeader(block, blockIndex).headerTitle;
}

/**
 * Versão simplificada: retorna apenas a categoria
 */
export function getBlockCategoryLabel(
  block: BlockLike
): string {
  const result = getBlockHeader(block, 0);
  return result.headerMeta ?? 'Sem categoria';
}

/**
 * Verifica se o bloco tem título real (não auto-gerado)
 */
export function hasRealTitle(block: BlockLike): boolean {
  const titleCandidate = firstNonEmpty(
    block.title,
    block.name,
    block.blockTitle,
    block.headerTitle
  );
  return titleCandidate !== null && !isAutoGeneratedTitle(titleCandidate);
}

/**
 * Verifica se o bloco tem categoria definida
 */
export function hasCategory(block: BlockLike): boolean {
  const category = firstNonEmpty(block.type, block.category);
  return category !== null;
}

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * MVP0 PATCH FINAL: normalizeRestLineForDisplay
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * Converte linhas de "Descanso X'" para "Intervalo X'" na exibição
 * para evitar confusão com "Descanso do dia".
 * 
 * REGRA ABSOLUTA: "Descanso" dentro de bloco = Intervalo técnico (não descanso do dia)
 * BADGE VISUAL: Sempre "Intervalo", NUNCA "Descanso"
 * 
 * @param text - Texto original da linha
 * @returns Texto normalizado para exibição
 */
export function normalizeRestLineForDisplay(text: string): string {
  if (!text) return text;
  
  const trimmed = text.trim();
  const lower = trimmed.toLowerCase();
  
  // ════════════════════════════════════════════════════════════════════════════
  // REGRA: Se a linha contém "Descanso" + tempo/número, converter para "Intervalo"
  // ════════════════════════════════════════════════════════════════════════════
  
  // A) "Descanso X'" / "Descanso X min" -> "Intervalo X'" / "Intervalo X min"
  if (/^descanso\s+\d+/i.test(lower)) {
    return trimmed.replace(/^descanso/i, 'Intervalo');
  }
  
  // B) "Descanso:" -> "Intervalo:"
  if (/^descanso\s*:/i.test(lower)) {
    return trimmed.replace(/^descanso/i, 'Intervalo');
  }
  
  // C) "Descanso entre rounds/séries" -> "Intervalo entre rounds/séries"
  if (/^descanso\s+(entre|between)/i.test(lower)) {
    return trimmed.replace(/^descanso/i, 'Intervalo');
  }
  
  // D) "Descanso de X min" -> "Intervalo de X min"
  if (/^descanso\s+de\s+\d+/i.test(lower)) {
    return trimmed.replace(/^descanso/i, 'Intervalo');
  }
  
  // E) "Descanso necessário/livre/ativo/passivo" -> "Intervalo necessário/..."
  if (/^descanso\s+(necess[aá]rio|livre|ativo|passivo|conforme)/i.test(lower)) {
    return trimmed.replace(/^descanso/i, 'Intervalo');
  }
  
  // F) "Descansar" -> "Intervalo" (para frases como "Descansar o necessário")
  if (/^descansar\b/i.test(lower)) {
    return trimmed.replace(/^descansar/i, 'Intervalo');
  }
  
  // G) "Descanso a cada X" -> "Intervalo a cada X"
  if (/^descanso\s+a\s+cada/i.test(lower)) {
    return trimmed.replace(/^descanso/i, 'Intervalo');
  }
  
  // H) "Rest X'" / "Rest X min" -> "Intervalo X'" / "Intervalo X min"
  if (/^rest\s+\d+/i.test(lower)) {
    return trimmed.replace(/^rest/i, 'Intervalo');
  }
  
  // I) "Rest between" -> "Intervalo between"
  if (/^rest\s+(between|as\s+needed)/i.test(lower)) {
    return trimmed.replace(/^rest/i, 'Intervalo');
  }
  
  // Não é padrão de descanso intra-bloco, retornar original
  return text;
}

/**
 * Verifica se uma linha é instrução de descanso intra-bloco
 * Usado para aplicar badge "INTERVALO" em vez de "DESCANSO"
 */
export function isInBlockRestInstruction(text: string): boolean {
  if (!text) return false;
  
  const lower = text.trim().toLowerCase();
  
  // Se contém "descanso" + dígito → é instrução intra-bloco
  if (/\bdescanso\b/i.test(lower) && /\d/.test(lower)) return true;
  
  // "Descansar" sempre é instrução
  if (/^descansar\b/i.test(lower)) return true;
  
  // "Descanso entre/de/a cada" são instruções
  if (/^descanso\s+(entre|between|de|a\s+cada|necess[aá]rio)/i.test(lower)) return true;
  
  // "Rest X'" é instrução
  if (/^rest\s+\d+/i.test(lower)) return true;
  
  // "Intervalo X'" já foi normalizado, também é instrução
  if (/^intervalo\s+\d+/i.test(lower)) return true;
  
  return false;
}

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * MVP0: SEPARAÇÃO VISUAL DE COMENTÁRIOS DO BLOCO
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * PRIORIDADE DE DADOS (ORDEM FIXA):
 * 1. Se existem tags [TREINO] e [COMENTÁRIO] → split determinístico por tags
 * 2. Se não existem tags → fallback para heurística de padrões
 * 
 * REGRA ABSOLUTA:
 * - Tags nunca aparecem na UI
 * - Comentário nunca se mistura com treino
 * - Sem heurística "por IA" ou "frases"
 */

export interface SeparatedBlockContent {
  exerciseLines: string[];
  commentLines: string[];
  headerLines?: string[]; // Linhas de header técnico (=)
}

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * MVP0: SPLIT DETERMINÍSTICO POR MARCADORES
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * MARCADORES OFICIAIS:
 * - `= TREINO` → Header do bloco de treino
 * - `-` → Item executável de treino
 * - `> COMENTÁRIO` ou `>` → Comentário do coach
 * 
 * REGRA DE FLUXO:
 * - Após `= TREINO`: linhas vão para treino
 * - Após `> COMENTÁRIO` ou `>`: linhas vão para comentário
 * - Linha `-` sempre é treino
 * - Linha `>` sempre é comentário
 * - Linha sem marcador segue o marcador de seção anterior
 */
type CurrentSection = 'treino' | 'comentario' | 'none';

function splitByMarkers(content: string): { 
  headerLines: string[]; 
  trainingLines: string[]; 
  commentLines: string[]; 
  invalidLines: string[];
  hasMarkers: boolean;
} {
  const lines = content.split('\n');
  const headerLines: string[] = [];
  const trainingLines: string[] = [];
  const commentLines: string[] = [];
  const invalidLines: string[] = [];
  
  let foundAnyMarker = false;
  let currentSection: CurrentSection = 'none';
  
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    
    // Detectar marcadores de SEÇÃO (= TREINO, > COMENTÁRIO)
    if (/^=\s*TREINO\b/i.test(trimmed)) {
      foundAnyMarker = true;
      currentSection = 'treino';
      headerLines.push(trimmed.replace(/^=\s*TREINO\s*/i, '').trim() || 'TREINO');
      continue;
    }
    
    if (/^>\s*COMENT[ÁA]RIO\b/i.test(trimmed)) {
      foundAnyMarker = true;
      currentSection = 'comentario';
      continue;
    }
    
    // Detectar marcadores de LINHA (-, >)
    if (trimmed.startsWith('-')) {
      foundAnyMarker = true;
      trainingLines.push(trimmed.slice(1).trim());
      continue;
    }
    
    if (trimmed.startsWith('>')) {
      foundAnyMarker = true;
      commentLines.push(trimmed.slice(1).trim());
      continue;
    }
    
    // Linha sem marcador explícito → segue a seção atual
    if (currentSection === 'treino') {
      trainingLines.push(trimmed);
    } else if (currentSection === 'comentario') {
      commentLines.push(trimmed);
    } else {
      // Nenhuma seção definida ainda
      invalidLines.push(trimmed);
    }
  }
  
  return {
    headerLines,
    trainingLines,
    commentLines,
    invalidLines,
    hasMarkers: foundAnyMarker,
  };
}

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * SPLIT POR TAGS [TREINO] / [COMENTÁRIO] — LEGADO
 * ═══════════════════════════════════════════════════════════════════════════
 */
function splitByTags(content: string): { treinoText: string; comentarioText: string; hasTags: boolean } {
  const treinoTag = '[TREINO]';
  const comentarioTag = '[COMENTÁRIO]';
  
  const hasTreinoTag = content.includes(treinoTag);
  const hasComentarioTag = content.includes(comentarioTag);
  
  // Se não tem nenhuma tag, retornar indicador de que não há tags
  if (!hasTreinoTag && !hasComentarioTag) {
    return { treinoText: content, comentarioText: '', hasTags: false };
  }
  
  let treinoText = '';
  let comentarioText = '';
  
  if (hasComentarioTag) {
    const comentarioStart = content.indexOf(comentarioTag);
    const comentarioContentStart = comentarioStart + comentarioTag.length;
    
    // TUDO depois de [COMENTÁRIO] é comentário - REGRA ABSOLUTA
    comentarioText = content.slice(comentarioContentStart).trim();
    
    // Treino é o que vem ANTES de [COMENTÁRIO]
    let prePart = content.slice(0, comentarioStart);
    
    // Se tem [TREINO], pegar conteúdo DEPOIS dela
    if (hasTreinoTag) {
      const treinoStart = prePart.indexOf(treinoTag);
      if (treinoStart !== -1) {
        treinoText = prePart.slice(treinoStart + treinoTag.length).trim();
      } else {
        treinoText = prePart.trim();
      }
    } else {
      treinoText = prePart.trim();
    }
  } else if (hasTreinoTag) {
    // Só [TREINO] existe: tudo depois é treino, comentário vazio
    const treinoStart = content.indexOf(treinoTag) + treinoTag.length;
    treinoText = content.slice(treinoStart).trim();
    comentarioText = '';
  }
  
  return { treinoText, comentarioText, hasTags: true };
}

/**
 * Detecta se uma linha é comentário/instrução do coach (fallback heurístico)
 * NOTA: Esta função só é usada quando NÃO há tags [TREINO]/[COMENTÁRIO]
 */
function isCommentLine(line: string): boolean {
  if (!line) return false;
  
  const trimmed = line.trim();
  if (!trimmed) return false;
  
  const lower = trimmed.toLowerCase();
  
  // A) Emoji de nota (legado) - SEMPRE é comentário
  if (trimmed.startsWith('📝')) {
    return true;
  }
  
  // B) Prefixos explícitos de comentário
  if (/^(nota|obs|observa[çc][aã]o|dica|aten[çc][aã]o|importante|lembrete|orienta[çc][aã]o)\s*:/i.test(lower)) {
    return true;
  }
  
  // C) Frases que terminam com "..." ou "…" (reticências indicam instrução aberta)
  if (/\.{2,}$/.test(trimmed) || /…$/.test(trimmed)) {
    return true;
  }
  
  // D) Padrões de instrução subjetiva
  const subjectivePatterns = [
    /o\s+necess[aá]rio/i,
    /conforme\s+(necess[aá]rio|poss[ií]vel|sentir)/i,
    /se\s+sentir/i,
    /manter\s+(o\s+)?ritmo/i,
    /foco\s+(em|no|na)/i,
    /priorizar/i,
    /aten[çc][aã]o\s+(ao|à|a)/i,
    /cuidado\s+(com|ao)/i,
    /lembrar\s+de/i,
    /n[aã]o\s+esquecer/i,
    /evitar/i,
    /tentar\s+(manter|n[aã]o|fazer)/i,
    /\bunbroken\b/i, // Instrução de execução "unbroken"
    /\bdescansar\b/i, // Instrução de descanso
  ];
  
  for (const pattern of subjectivePatterns) {
    if (pattern.test(lower)) {
      return true;
    }
  }
  
  // D) Linha sem números E sem estrutura de exercício
  const hasNumbers = /\d/.test(trimmed);
  const hasExercisePattern = /^(\d+|x\d+|\d+x)/i.test(lower) || 
    /\b(rep|reps|rounds?|sets?|series?|min|seg|sec|metros?|km|cal|calorias?)\b/i.test(lower);
  
  // Se não tem números NEM padrão de exercício, é provavelmente comentário
  // MAS precisa ter pelo menos 20 caracteres para evitar falsos positivos
  if (!hasNumbers && !hasExercisePattern && trimmed.length >= 20) {
    // Verificar se não é nome de exercício comum
    const exerciseNames = [
      /^(burpee|squat|deadlift|clean|snatch|press|push|pull|row|run|bike|ski|swim)/i,
      /^(agach|levantamento|remada|flexão|corrida|bicicleta)/i,
    ];
    
    const looksLikeExerciseName = exerciseNames.some(p => p.test(lower));
    if (!looksLikeExerciseName) {
      return true;
    }
  }
  
  return false;
}

// ════════════════════════════════════════════════════════════════════════════
// MVP0: REGRA DETERMINÍSTICA — LINHA EXECUTÁVEL
// ════════════════════════════════════════════════════════════════════════════
// Uma linha só é considerada TREINO se:
// 1) Contiver pelo menos UM número
// E
// 2) Contiver unidade ou estrutura válida (reps, x, m, km, s, min, PSE, Z1–Z5, EMOM, AMRAP, FOR TIME, rest)

const EXECUTABLE_UNITS_PATTERN = /(?:reps?|rep|x|m\b|km\b|s\b|seg\b|sec\b|min\b|minutos?\b|['']|PSE|RPE|Z[1-5]|Zona\s*[1-5]|EMOM|AMRAP|For\s*Time|RFT|Tabata|rest|descanso|rounds?|sets?|séries?|%|kg\b|lb\b|cal\b|calorias?\b|kcal\b)/i;

/**
 * Verifica se uma linha é EXECUTÁVEL (treino válido)
 * REGRA: Deve ter número + unidade/estrutura válida
 */
export function isExecutableLine(line: string): boolean {
  const trimmed = line.trim();
  
  // Linha vazia é ignorada (não conta como executável nem não-executável)
  if (!trimmed) return true;
  
  // REGRA 1: Deve conter pelo menos um número
  const hasNumber = /\d/.test(trimmed);
  if (!hasNumber) return false;
  
  // REGRA 2: Deve conter unidade ou estrutura válida
  const hasValidUnit = EXECUTABLE_UNITS_PATTERN.test(trimmed);
  
  return hasValidUnit;
}

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * FUNÇÃO PRINCIPAL: separateBlockContent
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * Separa o conteúdo do bloco em exercícios e comentários.
 * 
 * MVP0 REGRA CRÍTICA:
 * - exerciseLines APENAS contém linhas executáveis (com métrica)
 * - Linhas sem métrica são classificadas como comentário ou ignoradas
 * 
 * PRIORIDADE (COM FALLBACK):
 * 1. MARCADORES (=, -, >) — determinístico, sem heurística
 * 2. TAGS ([TREINO], [COMENTÁRIO]) — split por região
 * 3. HEURÍSTICA — padrões de comentário (fallback final)
 */
export function separateBlockContent(content: string): SeparatedBlockContent {
  if (!content) {
    return { exerciseLines: [], commentLines: [], headerLines: [] };
  }
  
  // ════════════════════════════════════════════════════════════════════════════
  // PRIORIDADE 1: MARCADORES (=, -, >) — DETERMINÍSTICO
  // Se encontrar qualquer marcador, usar modo determinístico
  // ════════════════════════════════════════════════════════════════════════════
  const markerResult = splitByMarkers(content);
  
  if (markerResult.hasMarkers) {
    // LOG obrigatório
    const blockSnippet = content.slice(0, 30).replace(/\n/g, ' ').trim();
    
    // MVP0: FILTRAR linhas NÃO executáveis das trainingLines
    const executableTrainingLines = markerResult.trainingLines.filter(l => isExecutableLine(l));
    const nonExecutableTrainingLines = markerResult.trainingLines.filter(l => l.trim() && !isExecutableLine(l));
    
    console.log(`[TAG_SPLIT] blockTitle="${blockSnippet}..." trainingLines=${executableTrainingLines.length} nonExec=${nonExecutableTrainingLines.length} commentLines=${markerResult.commentLines.length}`);
    
    // REGRA: Linhas sem marcador no modo determinístico vão para treino (fallback interno)
    // Isso permite transição gradual sem quebrar textos existentes
    // MVP0: Também filtrar invalidLines
    const executableInvalidLines = markerResult.invalidLines.filter(l => isExecutableLine(l));
    
    const exerciseLines = [
      ...markerResult.headerLines.map(h => `⚙️ ${h}`), // Header com emoji para destaque
      ...executableTrainingLines,
      ...executableInvalidLines,
    ].filter(l => l.length > 0);
    
    return {
      exerciseLines,
      commentLines: markerResult.commentLines,
      headerLines: markerResult.headerLines,
    };
  }
  
  // ════════════════════════════════════════════════════════════════════════════
  // PRIORIDADE 2: TAGS ([TREINO], [COMENTÁRIO]) — SPLIT POR REGIÃO
  // ════════════════════════════════════════════════════════════════════════════
  const { treinoText, comentarioText, hasTags } = splitByTags(content);
  
  if (hasTags) {
    const allTreinoLines = treinoText
      .split('\n')
      .map(l => l.trim())
      .filter(l => l.length > 0);
    
    // MVP0: FILTRAR linhas NÃO executáveis
    const exerciseLines = allTreinoLines.filter(l => isExecutableLine(l));
    const nonExecutableLines = allTreinoLines.filter(l => !isExecutableLine(l));
    
    const commentLines = comentarioText
      .split('\n')
      .map(l => l.trim())
      .filter(l => l.length > 0);
    
    // LOG
    const blockSnippet = content.slice(0, 30).replace(/\n/g, ' ').trim();
    console.log(`[TAG_SPLIT] blockTitle="${blockSnippet}..." trainingLines=${exerciseLines.length} nonExec=${nonExecutableLines.length} commentLines=${commentLines.length}`);
    
    return { exerciseLines, commentLines };
  }
  
  // ════════════════════════════════════════════════════════════════════════════
  // PRIORIDADE 3: HEURÍSTICA — FALLBACK FINAL
  // ════════════════════════════════════════════════════════════════════════════
  const lines = content.split('\n');
  const exerciseLines: string[] = [];
  const commentLines: string[] = [];
  
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    
    // MVP0: Primeiro verificar se é executável
    if (!isExecutableLine(trimmed)) {
      // Não é executável -> comentário
      commentLines.push(trimmed);
      continue;
    }
    
    if (isCommentLine(trimmed)) {
      commentLines.push(trimmed);
    } else {
      exerciseLines.push(trimmed);
    }
  }
  
  return { exerciseLines, commentLines };
}
