/**
 * blockDisplayUtils.ts - Utilitários para exibição de blocos de treino
 * 
 * ═══════════════════════════════════════════════════════════════════════════
 * MVP0: HEADER DO BLOCO = TÍTULO REAL (NUNCA "Bloco X" SE HÁ TÍTULO)
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * REGRA ÚNICA: O título real deve aparecer sempre que existir.
 * "Bloco X" é FALLBACK FINAL quando não há nenhum título preenchido.
 */

import { BLOCK_CATEGORIES } from '@/utils/categoryValidation';

/**
 * Interface flexível para aceitar diferentes estruturas de bloco
 */
interface BlockLike {
  title?: string | null;
  name?: string | null;
  blockTitle?: string | null;
  headerTitle?: string | null;
  type?: string | null;
  category?: string | null;
}

/**
 * Resultado do getBlockHeader
 */
export interface BlockHeaderResult {
  headerTitle: string;
  headerMeta: string | null;
}

/**
 * Helper para pegar o primeiro valor não-vazio de múltiplos candidatos
 */
function firstNonEmpty(...values: (string | null | undefined)[]): string | null {
  for (const v of values) {
    const trimmed = v?.trim();
    if (trimmed && trimmed.length > 0) {
      return trimmed;
    }
  }
  return null;
}

/**
 * Verifica se um título é auto-gerado ("Bloco X", "BLOCO X", "Treino")
 */
function isAutoGeneratedTitle(title: string | null | undefined): boolean {
  if (!title) return true;
  const trimmed = title.trim();
  if (!trimmed) return true;
  
  // Padrões considerados auto-gerados
  if (/^Bloco \d+$/i.test(trimmed)) return true;
  if (/^BLOCO \d+$/i.test(trimmed)) return true;
  if (trimmed.toLowerCase() === 'treino') return true;
  if (trimmed.toLowerCase() === 'novo bloco') return true;
  
  return false;
}

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * FUNÇÃO PRINCIPAL: getBlockHeader
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * Retorna { headerTitle, headerMeta } para uso em preview e tela do atleta.
 * 
 * REGRA:
 * - Se existe título real → mostrar título real
 * - Se não existe → fallback "Bloco X"
 * - headerMeta = categoria (se existir)
 */
export function getBlockHeader(block: BlockLike, index: number): BlockHeaderResult {
  // 1) Buscar título em múltiplos campos possíveis
  const titleCandidate = firstNonEmpty(
    block.title,
    block.name,
    block.blockTitle,
    block.headerTitle
  );
  
  // 2) Determinar displayTitle (ignorar auto-gerados)
  let displayTitle: string | null = null;
  if (titleCandidate && !isAutoGeneratedTitle(titleCandidate)) {
    displayTitle = titleCandidate;
  }
  
  // 3) Determinar categoria
  const categoryRaw = firstNonEmpty(block.type, block.category);
  let displayCategory: string | null = null;
  
  if (categoryRaw) {
    // Buscar label amigável na lista de categorias
    const categoryInfo = BLOCK_CATEGORIES.find(c => c.value === categoryRaw);
    displayCategory = categoryInfo ? categoryInfo.label : categoryRaw;
  }
  
  // 4) Header final
  const headerTitle = displayTitle ?? `Bloco ${index + 1}`;
  const headerMeta = displayCategory ?? null;
  
  return { headerTitle, headerMeta };
}

/**
 * Versão simplificada: retorna apenas o título
 */
export function getBlockDisplayTitle(
  block: BlockLike,
  blockIndex: number
): string {
  return getBlockHeader(block, blockIndex).headerTitle;
}

/**
 * Versão simplificada: retorna apenas a categoria
 */
export function getBlockCategoryLabel(
  block: BlockLike
): string {
  const result = getBlockHeader(block, 0);
  return result.headerMeta ?? 'Sem categoria';
}

/**
 * Verifica se o bloco tem título real (não auto-gerado)
 */
export function hasRealTitle(block: BlockLike): boolean {
  const titleCandidate = firstNonEmpty(
    block.title,
    block.name,
    block.blockTitle,
    block.headerTitle
  );
  return titleCandidate !== null && !isAutoGeneratedTitle(titleCandidate);
}

/**
 * Verifica se o bloco tem categoria definida
 */
export function hasCategory(block: BlockLike): boolean {
  const category = firstNonEmpty(block.type, block.category);
  return category !== null;
}

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * MVP0 PATCH FINAL: normalizeRestLineForDisplay
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * Converte linhas de "Descanso X'" para "Intervalo X'" na exibição
 * para evitar confusão com "Descanso do dia".
 * 
 * REGRA ABSOLUTA: "Descanso" dentro de bloco = Intervalo técnico (não descanso do dia)
 * BADGE VISUAL: Sempre "Intervalo", NUNCA "Descanso"
 * 
 * @param text - Texto original da linha
 * @returns Texto normalizado para exibição
 */
export function normalizeRestLineForDisplay(text: string): string {
  if (!text) return text;
  
  const trimmed = text.trim();
  const lower = trimmed.toLowerCase();
  
  // ════════════════════════════════════════════════════════════════════════════
  // REGRA: Se a linha contém "Descanso" + tempo/número, converter para "Intervalo"
  // ════════════════════════════════════════════════════════════════════════════
  
  // A) "Descanso X'" / "Descanso X min" -> "Intervalo X'" / "Intervalo X min"
  if (/^descanso\s+\d+/i.test(lower)) {
    return trimmed.replace(/^descanso/i, 'Intervalo');
  }
  
  // B) "Descanso:" -> "Intervalo:"
  if (/^descanso\s*:/i.test(lower)) {
    return trimmed.replace(/^descanso/i, 'Intervalo');
  }
  
  // C) "Descanso entre rounds/séries" -> "Intervalo entre rounds/séries"
  if (/^descanso\s+(entre|between)/i.test(lower)) {
    return trimmed.replace(/^descanso/i, 'Intervalo');
  }
  
  // D) "Descanso de X min" -> "Intervalo de X min"
  if (/^descanso\s+de\s+\d+/i.test(lower)) {
    return trimmed.replace(/^descanso/i, 'Intervalo');
  }
  
  // E) "Descanso necessário/livre/ativo/passivo" -> "Intervalo necessário/..."
  if (/^descanso\s+(necess[aá]rio|livre|ativo|passivo|conforme)/i.test(lower)) {
    return trimmed.replace(/^descanso/i, 'Intervalo');
  }
  
  // F) "Descansar" -> "Intervalo" (para frases como "Descansar o necessário")
  if (/^descansar\b/i.test(lower)) {
    return trimmed.replace(/^descansar/i, 'Intervalo');
  }
  
  // G) "Descanso a cada X" -> "Intervalo a cada X"
  if (/^descanso\s+a\s+cada/i.test(lower)) {
    return trimmed.replace(/^descanso/i, 'Intervalo');
  }
  
  // H) "Rest X'" / "Rest X min" -> "Intervalo X'" / "Intervalo X min"
  if (/^rest\s+\d+/i.test(lower)) {
    return trimmed.replace(/^rest/i, 'Intervalo');
  }
  
  // I) "Rest between" -> "Intervalo between"
  if (/^rest\s+(between|as\s+needed)/i.test(lower)) {
    return trimmed.replace(/^rest/i, 'Intervalo');
  }
  
  // Não é padrão de descanso intra-bloco, retornar original
  return text;
}

/**
 * Verifica se uma linha é instrução de descanso intra-bloco
 * Usado para aplicar badge "INTERVALO" em vez de "DESCANSO"
 */
export function isInBlockRestInstruction(text: string): boolean {
  if (!text) return false;
  
  const lower = text.trim().toLowerCase();
  
  // Se contém "descanso" + dígito → é instrução intra-bloco
  if (/\bdescanso\b/i.test(lower) && /\d/.test(lower)) return true;
  
  // "Descansar" sempre é instrução
  if (/^descansar\b/i.test(lower)) return true;
  
  // "Descanso entre/de/a cada" são instruções
  if (/^descanso\s+(entre|between|de|a\s+cada|necess[aá]rio)/i.test(lower)) return true;
  
  // "Rest X'" é instrução
  if (/^rest\s+\d+/i.test(lower)) return true;
  
  // "Intervalo X'" já foi normalizado, também é instrução
  if (/^intervalo\s+\d+/i.test(lower)) return true;
  
  return false;
}

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * MVP0: SEPARAÇÃO VISUAL DE COMENTÁRIOS DO BLOCO
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * PRIORIDADE DE DADOS (ORDEM FIXA):
 * 1. Se existem tags [TREINO] e [COMENTÁRIO] → split determinístico por tags
 * 2. Se não existem tags → fallback para heurística de padrões
 * 
 * REGRA ABSOLUTA:
 * - Tags nunca aparecem na UI
 * - Comentário nunca se mistura com treino
 * - Sem heurística "por IA" ou "frases"
 */

export interface SeparatedBlockContent {
  exerciseLines: string[];
  commentLines: string[];
}

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * SPLIT DETERMINÍSTICO POR TAGS [TREINO] / [COMENTÁRIO]
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * REGRAS:
 * - Tudo entre [TREINO] e [COMENTÁRIO] é treino
 * - Tudo depois de [COMENTÁRIO] é comentário até o fim
 * - Se faltar [COMENTÁRIO], comentário = vazio
 * - Se faltar [TREINO], treino = texto inteiro (fallback) e comentário vazio
 * - Tags são removidas do output
 */
function splitByTags(content: string): { treinoText: string; comentarioText: string; hasTags: boolean } {
  const treinoTag = '[TREINO]';
  const comentarioTag = '[COMENTÁRIO]';
  
  const hasTreinoTag = content.includes(treinoTag);
  const hasComentarioTag = content.includes(comentarioTag);
  
  // Se não tem nenhuma tag, retornar indicador de que não há tags
  if (!hasTreinoTag && !hasComentarioTag) {
    return { treinoText: content, comentarioText: '', hasTags: false };
  }
  
  let treinoText = '';
  let comentarioText = '';
  
  if (hasTreinoTag && hasComentarioTag) {
    // Caso ideal: ambas as tags existem
    const treinoStart = content.indexOf(treinoTag) + treinoTag.length;
    const comentarioStart = content.indexOf(comentarioTag);
    const comentarioContentStart = comentarioStart + comentarioTag.length;
    
    // Treino = entre [TREINO] e [COMENTÁRIO]
    treinoText = content.slice(treinoStart, comentarioStart).trim();
    // Comentário = tudo depois de [COMENTÁRIO]
    comentarioText = content.slice(comentarioContentStart).trim();
  } else if (hasTreinoTag && !hasComentarioTag) {
    // Só [TREINO] existe: tudo depois é treino, comentário vazio
    const treinoStart = content.indexOf(treinoTag) + treinoTag.length;
    treinoText = content.slice(treinoStart).trim();
    comentarioText = '';
  } else if (!hasTreinoTag && hasComentarioTag) {
    // Só [COMENTÁRIO] existe: tudo antes é treino, tudo depois é comentário
    const comentarioStart = content.indexOf(comentarioTag);
    const comentarioContentStart = comentarioStart + comentarioTag.length;
    treinoText = content.slice(0, comentarioStart).trim();
    comentarioText = content.slice(comentarioContentStart).trim();
  }
  
  return { treinoText, comentarioText, hasTags: true };
}

/**
 * Detecta se uma linha é comentário/instrução do coach (fallback heurístico)
 */
function isCommentLine(line: string): boolean {
  if (!line) return false;
  
  const trimmed = line.trim();
  if (!trimmed) return false;
  
  const lower = trimmed.toLowerCase();
  
  // A) Prefixos explícitos de comentário
  if (/^(nota|obs|observa[çc][aã]o|dica|aten[çc][aã]o|importante|lembrete|orienta[çc][aã]o)\s*:/i.test(lower)) {
    return true;
  }
  
  // B) Frases que terminam com "..." (reticências indicam instrução aberta)
  if (/\.{2,}$/.test(trimmed) || /…$/.test(trimmed)) {
    return true;
  }
  
  // C) Frases com padrões de instrução subjetiva
  const subjectivePatterns = [
    /o\s+necess[aá]rio/i,
    /conforme\s+(necess[aá]rio|poss[ií]vel|sentir)/i,
    /se\s+sentir/i,
    /manter\s+(o\s+)?ritmo/i,
    /foco\s+(em|no|na)/i,
    /priorizar/i,
    /aten[çc][aã]o\s+(ao|à|a)/i,
    /cuidado\s+(com|ao)/i,
    /lembrar\s+de/i,
    /n[aã]o\s+esquecer/i,
    /evitar/i,
    /tentar\s+(manter|n[aã]o|fazer)/i,
  ];
  
  for (const pattern of subjectivePatterns) {
    if (pattern.test(lower)) {
      return true;
    }
  }
  
  // D) Linha sem números E sem estrutura de exercício
  const hasNumbers = /\d/.test(trimmed);
  const hasExercisePattern = /^(\d+|x\d+|\d+x)/i.test(lower) || 
    /\b(rep|reps|rounds?|sets?|series?|min|seg|sec|metros?|km|cal|calorias?)\b/i.test(lower);
  
  // Se não tem números NEM padrão de exercício, é provavelmente comentário
  // MAS precisa ter pelo menos 20 caracteres para evitar falsos positivos
  if (!hasNumbers && !hasExercisePattern && trimmed.length >= 20) {
    // Verificar se não é nome de exercício comum
    const exerciseNames = [
      /^(burpee|squat|deadlift|clean|snatch|press|push|pull|row|run|bike|ski|swim)/i,
      /^(agach|levantamento|remada|flexão|corrida|bicicleta)/i,
    ];
    
    const looksLikeExerciseName = exerciseNames.some(p => p.test(lower));
    if (!looksLikeExerciseName) {
      return true;
    }
  }
  
  return false;
}

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * FUNÇÃO PRINCIPAL: separateBlockContent
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * Separa o conteúdo do bloco em exercícios e comentários.
 * 
 * PRIORIDADE:
 * 1. Split determinístico por tags [TREINO] / [COMENTÁRIO] se existirem
 * 2. Fallback heurístico se não existirem tags
 */
export function separateBlockContent(content: string): SeparatedBlockContent {
  if (!content) {
    return { exerciseLines: [], commentLines: [] };
  }
  
  // 1. Tentar split por tags (determinístico)
  const { treinoText, comentarioText, hasTags } = splitByTags(content);
  
  // Log de diagnóstico (formato curto conforme especificação)
  const blockSnippet = content.slice(0, 30).replace(/\n/g, ' ').trim();
  console.log(`[UI_SPLIT] title="${blockSnippet}${content.length > 30 ? '...' : ''}" hasTags=${hasTags} trainChars=${treinoText.length} commentChars=${comentarioText.length}`);
  
  if (hasTags) {
    // Split por tags: direto, sem heurística
    const exerciseLines = treinoText.split('\n').map(l => l.trim()).filter(l => l.length > 0);
    const commentLines = comentarioText.split('\n').map(l => l.trim()).filter(l => l.length > 0);
    
    return { exerciseLines, commentLines };
  }
  
  // 2. Fallback: heurística por padrões (texto sem tags)
  const lines = content.split('\n');
  const exerciseLines: string[] = [];
  const commentLines: string[] = [];
  
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue; // Ignorar linhas vazias
    
    if (isCommentLine(trimmed)) {
      commentLines.push(trimmed);
    } else {
      exerciseLines.push(trimmed);
    }
  }
  
  return { exerciseLines, commentLines };
}
