/**
 * blockDisplayUtils.ts - Utilitários para exibição de blocos de treino
 * 
 * ═══════════════════════════════════════════════════════════════════════════════
 * MODELO DETERMINÍSTICO DE SEPARAÇÃO TREINO vs COMENTÁRIO (MVP0)
 * ═══════════════════════════════════════════════════════════════════════════════
 * 
 * O motor NÃO interpreta texto. O motor APENAS classifica por MARCADOR.
 * 
 * MARCADORES OFICIAIS:
 * - `= TREINO` → Início do bloco de treino (header)
 * - `-` → Item executável de treino (deve ter métrica objetiva)
 * - `> COMENTÁRIO` ou `>` → Observação do coach
 * 
 * REGRA DE FLUXO:
 * - Texto após `= TREINO` é treino até encontrar `>`
 * - Texto após `>` é comentário até mudar o marcador
 * - Linha sem marcador segue o marcador anterior
 * 
 * FALLBACKS (para textos legados):
 * 1. TAGS: [TREINO], [COMENTÁRIO] — split por região
 * 2. HEURÍSTICA: padrões de comentário (último recurso)
 * 
 * REGRA CRÍTICA:
 * - Comentário NUNCA passa por parser de treino
 * - Comentário NUNCA vira exercício
 * - Linha de treino sem métrica = WARNING
 */

import { BLOCK_CATEGORIES } from '@/utils/categoryValidation';

/**
 * Interface flexível para aceitar diferentes estruturas de bloco
 */
interface BlockLike {
  title?: string | null;
  name?: string | null;
  blockTitle?: string | null;
  headerTitle?: string | null;
  type?: string | null;
  category?: string | null;
}

/**
 * Resultado do getBlockHeader
 */
export interface BlockHeaderResult {
  headerTitle: string;
  headerMeta: string | null;
}

/**
 * Helper para pegar o primeiro valor não-vazio de múltiplos candidatos
 */
function firstNonEmpty(...values: (string | null | undefined)[]): string | null {
  for (const v of values) {
    const trimmed = v?.trim();
    if (trimmed && trimmed.length > 0) {
      return trimmed;
    }
  }
  return null;
}

/**
 * Verifica se um título é auto-gerado ("Bloco X", "BLOCO X", "Treino")
 */
function isAutoGeneratedTitle(title: string | null | undefined): boolean {
  if (!title) return true;
  const trimmed = title.trim();
  if (!trimmed) return true;
  
  // Padrões considerados auto-gerados
  if (/^Bloco \d+$/i.test(trimmed)) return true;
  if (/^BLOCO \d+$/i.test(trimmed)) return true;
  if (trimmed.toLowerCase() === 'treino') return true;
  if (trimmed.toLowerCase() === 'novo bloco') return true;
  
  return false;
}

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * FUNÇÃO PRINCIPAL: getBlockHeader
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * Retorna { headerTitle, headerMeta } para uso em preview e tela do atleta.
 * 
 * REGRA:
 * - Se existe título real → mostrar título real
 * - Se não existe → fallback "Bloco X"
 * - headerMeta = categoria (se existir)
 */
export function getBlockHeader(block: BlockLike, index: number): BlockHeaderResult {
  // 1) Buscar título em múltiplos campos possíveis
  const titleCandidate = firstNonEmpty(
    block.title,
    block.name,
    block.blockTitle,
    block.headerTitle
  );
  
  // 2) Determinar displayTitle (ignorar auto-gerados)
  let displayTitle: string | null = null;
  if (titleCandidate && !isAutoGeneratedTitle(titleCandidate)) {
    displayTitle = titleCandidate;
  }
  
  // 3) Determinar categoria
  const categoryRaw = firstNonEmpty(block.type, block.category);
  let displayCategory: string | null = null;
  
  if (categoryRaw) {
    // Buscar label amigável na lista de categorias
    const categoryInfo = BLOCK_CATEGORIES.find(c => c.value === categoryRaw);
    displayCategory = categoryInfo ? categoryInfo.label : categoryRaw;
  }
  
  // 4) Header final
  const headerTitle = displayTitle ?? `Bloco ${index + 1}`;
  const headerMeta = displayCategory ?? null;
  
  return { headerTitle, headerMeta };
}

/**
 * Versão simplificada: retorna apenas o título
 */
export function getBlockDisplayTitle(
  block: BlockLike,
  blockIndex: number
): string {
  return getBlockHeader(block, blockIndex).headerTitle;
}

/**
 * Versão simplificada: retorna apenas a categoria
 */
export function getBlockCategoryLabel(
  block: BlockLike
): string {
  const result = getBlockHeader(block, 0);
  return result.headerMeta ?? 'Sem categoria';
}

/**
 * Verifica se o bloco tem título real (não auto-gerado)
 */
export function hasRealTitle(block: BlockLike): boolean {
  const titleCandidate = firstNonEmpty(
    block.title,
    block.name,
    block.blockTitle,
    block.headerTitle
  );
  return titleCandidate !== null && !isAutoGeneratedTitle(titleCandidate);
}

/**
 * Verifica se o bloco tem categoria definida
 */
export function hasCategory(block: BlockLike): boolean {
  const category = firstNonEmpty(block.type, block.category);
  return category !== null;
}

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * MVP0 PATCH FINAL: normalizeRestLineForDisplay
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * Converte linhas de "Descanso X'" para "Intervalo X'" na exibição
 * para evitar confusão com "Descanso do dia".
 * 
 * REGRA ABSOLUTA: "Descanso" dentro de bloco = Intervalo técnico (não descanso do dia)
 * BADGE VISUAL: Sempre "Intervalo", NUNCA "Descanso"
 * 
 * @param text - Texto original da linha
 * @returns Texto normalizado para exibição
 */
export function normalizeRestLineForDisplay(text: string): string {
  if (!text) return text;
  
  const trimmed = text.trim();
  const lower = trimmed.toLowerCase();
  
  // ════════════════════════════════════════════════════════════════════════════
  // REGRA: Se a linha contém "Descanso" + tempo/número, converter para "Intervalo"
  // ════════════════════════════════════════════════════════════════════════════
  
  // A) "Descanso X'" / "Descanso X min" -> "Intervalo X'" / "Intervalo X min"
  if (/^descanso\s+\d+/i.test(lower)) {
    return trimmed.replace(/^descanso/i, 'Intervalo');
  }
  
  // B) "Descanso:" -> "Intervalo:"
  if (/^descanso\s*:/i.test(lower)) {
    return trimmed.replace(/^descanso/i, 'Intervalo');
  }
  
  // C) "Descanso entre rounds/séries" -> "Intervalo entre rounds/séries"
  if (/^descanso\s+(entre|between)/i.test(lower)) {
    return trimmed.replace(/^descanso/i, 'Intervalo');
  }
  
  // D) "Descanso de X min" -> "Intervalo de X min"
  if (/^descanso\s+de\s+\d+/i.test(lower)) {
    return trimmed.replace(/^descanso/i, 'Intervalo');
  }
  
  // E) "Descanso necessário/livre/ativo/passivo" -> "Intervalo necessário/..."
  if (/^descanso\s+(necess[aá]rio|livre|ativo|passivo|conforme)/i.test(lower)) {
    return trimmed.replace(/^descanso/i, 'Intervalo');
  }
  
  // F) "Descansar" -> "Intervalo" (para frases como "Descansar o necessário")
  if (/^descansar\b/i.test(lower)) {
    return trimmed.replace(/^descansar/i, 'Intervalo');
  }
  
  // G) "Descanso a cada X" -> "Intervalo a cada X"
  if (/^descanso\s+a\s+cada/i.test(lower)) {
    return trimmed.replace(/^descanso/i, 'Intervalo');
  }
  
  // H) "Rest X'" / "Rest X min" -> "Intervalo X'" / "Intervalo X min"
  if (/^rest\s+\d+/i.test(lower)) {
    return trimmed.replace(/^rest/i, 'Intervalo');
  }
  
  // I) "Rest between" -> "Intervalo between"
  if (/^rest\s+(between|as\s+needed)/i.test(lower)) {
    return trimmed.replace(/^rest/i, 'Intervalo');
  }
  
  // Não é padrão de descanso intra-bloco, retornar original
  return text;
}

/**
 * Verifica se uma linha é instrução de descanso intra-bloco
 * Usado para aplicar badge "INTERVALO" em vez de "DESCANSO"
 */
export function isInBlockRestInstruction(text: string): boolean {
  if (!text) return false;
  
  const lower = text.trim().toLowerCase();
  
  // Se contém "descanso" + dígito → é instrução intra-bloco
  if (/\bdescanso\b/i.test(lower) && /\d/.test(lower)) return true;
  
  // "Descansar" sempre é instrução
  if (/^descansar\b/i.test(lower)) return true;
  
  // "Descanso entre/de/a cada" são instruções
  if (/^descanso\s+(entre|between|de|a\s+cada|necess[aá]rio)/i.test(lower)) return true;
  
  // "Rest X'" é instrução
  if (/^rest\s+\d+/i.test(lower)) return true;
  
  // "Intervalo X'" já foi normalizado, também é instrução
  if (/^intervalo\s+\d+/i.test(lower)) return true;
  
  return false;
}

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * MVP0 REGRA FINAL: SEPARAÇÃO TREINO vs COMENTÁRIO (100% DETERMINÍSTICA)
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * EXERCÍCIO (linha executável):
 * - Só é exercício se a linha começar com "- " (hífen + espaço)
 * 
 * COMENTÁRIO:
 * - Qualquer trecho entre parênteses "(...)" é comentário
 * - Comentário NUNCA vira exercício
 * - Comentário NÃO altera o motor
 * 
 * SEÇÃO "> COMENTÁRIO":
 * - Define que comentários abaixo vão para o sub-bloco visual
 * - Texto dentro de "> COMENTÁRIO" que NÃO estiver entre "( )" gera ALERTA
 */

export interface ParseAlert {
  type: 'MISSING_DASH' | 'COMMENT_NOT_IN_PARENS';
  message: string;
  line: string;
  lineIndex: number;
}

export interface InlineComment {
  lineIndex: number;
  text: string;
}

export interface SeparatedBlockContent {
  exerciseLines: string[];
  commentLines: string[]; // Alias for coachNotes (backward compat)
  coachNotes: string[];   // Comentários da seção "> COMENTÁRIO"
  inlineComments: InlineComment[]; // Comentários inline fora de "> COMENTÁRIO"
  alerts: ParseAlert[];
  headerLines?: string[];
}

// Padrão para detectar texto entre parênteses
const PARENTHESES_PATTERN = /\([^)]+\)/g;

// Padrão para detectar linhas que "parecem exercício"
const LOOKS_LIKE_EXERCISE_PATTERN = /^(\d+|reps?|x\d+|\d+x)|(?:reps?|x|m\b|km\b|cal\b|kg\b|lb\b|PSE|RPE|EMOM|AMRAP|for\s*time)/i;

/**
 * Extrai todos os comentários entre parênteses de uma linha
 * Retorna o texto sem os parênteses e os comentários extraídos
 */
function extractParenthesesComments(line: string): { cleanLine: string; comments: string[] } {
  const comments: string[] = [];
  const matches = line.match(PARENTHESES_PATTERN);
  
  if (matches) {
    for (const match of matches) {
      // Remove os parênteses e guarda o conteúdo
      const content = match.slice(1, -1).trim();
      if (content) {
        comments.push(content);
      }
    }
  }
  
  // Remove todos os parênteses da linha
  const cleanLine = line.replace(PARENTHESES_PATTERN, '').trim();
  
  return { cleanLine, comments };
}

/**
 * Detecta se uma linha parece exercício (para gerar alerta MISSING_DASH)
 */
function looksLikeExercise(line: string): boolean {
  const trimmed = line.trim();
  if (!trimmed) return false;
  
  // Começa com número
  if (/^\d/.test(trimmed)) return true;
  
  // Contém padrões de exercício
  if (LOOKS_LIKE_EXERCISE_PATTERN.test(trimmed)) return true;
  
  return false;
}

/**
 * Verifica se uma linha é título de bloco (all caps ou padrão específico)
 */
function isBlockTitle(line: string): boolean {
  const trimmed = line.trim();
  if (!trimmed) return false;
  
  // All caps (mais de 2 palavras ou palavra única >= 4 letras)
  if (/^[A-ZÁÀÂÃÉÈÊÍÌÎÓÒÔÕÚÙÛÇ\s]+$/.test(trimmed) && trimmed.length >= 4) {
    return true;
  }
  
  // Padrões de título conhecidos
  if (/^(AQUECIMENTO|FORÇA|WOD|TÉCNICO|CARDIO|MOBILIDADE|SKILL|METCON|COOL\s*DOWN)/i.test(trimmed)) {
    return true;
  }
  
  return false;
}

/**
 * Detecta início da seção de comentário
 */
function isCommentSectionStart(line: string): boolean {
  const trimmed = line.trim();
  // Aceita: "> COMENTÁRIO", ">COMENTÁRIO", "COMENTÁRIO", "> COMENTARIO"
  return /^>?\s*COMENT[ÁA]RIO$/i.test(trimmed);
}

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * FUNÇÃO PRINCIPAL: separateBlockContent (MVP0 REGRA FINAL)
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * Input: block.content (texto bruto)
 * Output:
 *   - exerciseLines: string[] (apenas linhas que começam com "- ")
 *   - coachNotes: string[] (comentários dentro de "> COMENTÁRIO")
 *   - inlineComments: InlineComment[] (comentários fora de "> COMENTÁRIO")
 *   - alerts: ParseAlert[]
 */
export function separateBlockContent(content: string): SeparatedBlockContent {
  if (!content) {
    return { 
      exerciseLines: [], 
      commentLines: [], 
      coachNotes: [],
      inlineComments: [],
      alerts: [],
      headerLines: [] 
    };
  }
  
  const lines = content.split('\n');
  const exerciseLines: string[] = [];
  const coachNotes: string[] = [];
  const inlineComments: InlineComment[] = [];
  const alerts: ParseAlert[] = [];
  const headerLines: string[] = [];
  
  let inCommentSection = false;
  
  for (let lineIndex = 0; lineIndex < lines.length; lineIndex++) {
    const rawLine = lines[lineIndex];
    const trimmed = rawLine.trim();
    
    // Linha vazia - ignorar
    if (!trimmed) continue;
    
    // ═══════════════════════════════════════════════════════════════════════════
    // DETECTAR INÍCIO/FIM DA SEÇÃO "> COMENTÁRIO"
    // ═══════════════════════════════════════════════════════════════════════════
    if (isCommentSectionStart(trimmed)) {
      inCommentSection = true;
      continue; // Não renderizar a linha "> COMENTÁRIO" em si
    }
    
    // Novo título de bloco encerra seção de comentário
    if (isBlockTitle(trimmed) && !trimmed.startsWith('-')) {
      inCommentSection = false;
      // Títulos de bloco são headers
      headerLines.push(trimmed);
      continue;
    }
    
    // ═══════════════════════════════════════════════════════════════════════════
    // EXTRAIR COMENTÁRIOS ENTRE PARÊNTESES
    // ═══════════════════════════════════════════════════════════════════════════
    const { cleanLine, comments } = extractParenthesesComments(trimmed);
    
    // Guardar comentários extraídos
    for (const comment of comments) {
      if (inCommentSection) {
        coachNotes.push(comment);
      } else {
        inlineComments.push({ lineIndex, text: comment });
      }
    }
    
    // ═══════════════════════════════════════════════════════════════════════════
    // CLASSIFICAR A LINHA (APÓS REMOVER PARÊNTESES)
    // ═══════════════════════════════════════════════════════════════════════════
    
    // Linha vazia após remover parênteses - só tinha comentário
    if (!cleanLine) continue;
    
    // ─────────────────────────────────────────────────────────────────────────
    // DENTRO DE "> COMENTÁRIO"
    // ─────────────────────────────────────────────────────────────────────────
    if (inCommentSection) {
      // Texto dentro de "> COMENTÁRIO" que NÃO estava em parênteses → ALERTA
      alerts.push({
        type: 'COMMENT_NOT_IN_PARENS',
        message: 'Dentro de > COMENTÁRIO, todo comentário deve estar entre ( ).',
        line: trimmed,
        lineIndex
      });
      continue;
    }
    
    // ─────────────────────────────────────────────────────────────────────────
    // FORA DE "> COMENTÁRIO"
    // ─────────────────────────────────────────────────────────────────────────
    
    // EXERCÍCIO: Linha começa com "- "
    if (cleanLine.startsWith('- ') || cleanLine.startsWith('-')) {
      // Remove o hífen e espaço iniciais
      const exerciseText = cleanLine.replace(/^-\s*/, '').trim();
      if (exerciseText) {
        exerciseLines.push(exerciseText);
      }
      continue;
    }
    
    // É título de bloco? (já tratado acima, mas double-check)
    if (isBlockTitle(cleanLine)) {
      headerLines.push(cleanLine);
      continue;
    }
    
    // PARECE EXERCÍCIO MAS NÃO TEM HÍFEN → ALERTA
    if (looksLikeExercise(cleanLine)) {
      alerts.push({
        type: 'MISSING_DASH',
        message: "Linha parece exercício, mas precisa começar com '- '. Corrija para não afetar o motor.",
        line: trimmed,
        lineIndex
      });
      // Não adiciona como exercício NEM como comentário - só alerta
      continue;
    }
    
    // Qualquer outra linha fora de seção → ignorar silenciosamente
    // (não é exercício, não é comentário, não é título)
  }
  
  // ═══════════════════════════════════════════════════════════════════════════
  // LOG DE VERIFICAÇÃO (OBRIGATÓRIO PARA DEBUG)
  // ═══════════════════════════════════════════════════════════════════════════
  const blockSnippet = content.slice(0, 40).replace(/\n/g, ' ').trim();
  console.log(`[PARSE_RESULT] blockTitle="${blockSnippet}..." exerciseLines=${exerciseLines.length}, inlineComments=${inlineComments.length}, coachNotes=${coachNotes.length}, alerts=${alerts.length}`);
  
  if (alerts.length > 0) {
    console.log(`[PARSE_ALERTS]`, alerts.map(a => `${a.type}: "${a.line}"`).join('; '));
  }
  
  return { 
    exerciseLines, 
    commentLines: coachNotes, // Backward compatibility
    coachNotes,
    inlineComments,
    alerts,
    headerLines 
  };
}

// ════════════════════════════════════════════════════════════════════════════
// LEGACY EXPORTS (backward compatibility)
// ════════════════════════════════════════════════════════════════════════════

/**
 * Verifica se uma linha é EXECUTÁVEL (treino válido)
 * MVP0: Agora só verifica se começa com "- "
 */
export function isExecutableLine(line: string): boolean {
  const trimmed = line.trim();
  if (!trimmed) return true; // Linha vazia é "válida" (não bloqueia)
  return trimmed.startsWith('- ') || trimmed.startsWith('-');
}
